# Generated by Django 4.0 on 2021-12-22 18:06

import crmapi.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isAdmin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=crmapi.models.get_image_path)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmapi.user')),
            ],
        ),
    ]
