# Generated by Django 4.0 on 2021-12-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapi', '0003_alter_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_modifier',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
